"""empty message

Revision ID: bbb9a4c736e3
Revises: 2fbcdbdd4a0a
Create Date: 2022-05-31 14:10:59.158206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb9a4c736e3'
down_revision = '2fbcdbdd4a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('channel_uuid', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'channels', ['channel_uuid'])
    op.add_column('inbox_channels', sa.Column('inbox_uuid', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'inbox_channels', ['inbox_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox_channels', type_='unique')
    op.drop_column('inbox_channels', 'inbox_uuid')
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_column('channels', 'channel_uuid')
    # ### end Alembic commands ###
